feat: Add envs variables verification

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,6 +22,17 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Check Required Secrets
+        run: |
+          if [ -z "${{ secrets.NEXT_PUBLIC_CDN_BASE_URL }}" ]; then
+            echo "ERROR: NEXT_PUBLIC_CDN_BASE_URL secret is missing!"
+            exit 1
+          fi
+          if [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ]; then
+            echo "ERROR: NEXT_PUBLIC_SUPABASE_URL secret is missing!"
+            exit 1
+          fi
+
       - name: Install pnpm
         uses: pnpm/action-setup@v4
         with:
